#!/usr/bin/env bash

rm -rf src
mkdir src
cp -R $1 src/HaloMD.app
cp -R Install.rtfd src/
../vendor/create-dmg/create-dmg --volname "HaloMD" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon HaloMD.app 200 190 --hide-extension HaloMD.app --hide-extension Install.rtfd --app-drop-link 600 185 $2 src/
rm -rf src
